In [3]:
import numpy as np

def loadDataset():
    postringList =[
        ['my','dog','has','flea','problems','help','please'],
        ['maybe','not','take','him','to','dog','park','stupid'],
        ['my','dalmation','is','so','cute','I','love','him'],
        ['stop','posting','stupid','worthless','garbage'],
        ['mr','licsk','ate','my','steak','how','to','stop','him'],
        ['quit','buying','worthless','dog','food','stupid']
    ]
    classVec = [0,1,0,1,0,1] # 1은 폭력적인것, 0은 폭력적이지 않은 것
    return postringList,classVec

def createVocabList(dataSet):
    vocabSet = set()
    for document in dataSet:
        vocabSet = vocabSet | set(document) # 합집합을 생성
    return list(vocabSet)

def sentence2vec(tokens,sentence):
    returnVec = [0] * len(tokens) # vccabList 의 길이만큼 0을 가진 vector 생성
    for word in sentence:
        if word in tokens:
            returnVec[tokens.index(word)] = 1
        else:
            print("The word : {} is not in my Vocabulary!".format(word))
    return returnVec

def makeDataSet(tokens,sentences):
    # return word matrixx
    wordMatrix =[]
    for sentence in sentences:
        wordVec = sentence2vec(tokens,sentence)
        wordMatrix.append(wordVec)
    return np.array(wordMatrix)

In [4]:
sentences, lables = loadDataset()
tokens = createVocabList(sentences)
wordVec = sentence2vec(tokens,sentences[0])

dataSet = makeDataSet(tokens,sentences)
lables = np.array(lables)
print(tokens)
print(dataSet)

['dalmation', 'dog', 'buying', 'stop', 'my', 'I', 'quit', 'problems', 'ate', 'cute', 'please', 'flea', 'so', 'food', 'take', 'him', 'to', 'steak', 'stupid', 'love', 'posting', 'maybe', 'worthless', 'has', 'help', 'garbage', 'how', 'not', 'mr', 'licsk', 'is', 'park']
[[0 1 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1]
 [1 0 0 0 1 1 0 0 0 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0]
 [0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0]]


In [8]:
def classify(dataSet,lables,testVec,k=0.1):
    m = dataSet.shape[0]
    unique_lable = np.unique(lables)
    lable_num = unique_lable.shape[0]
    
    prob_per_classes = []
    Idx2Lable = {}
    index = 0
    for lable in unique_lable:
        Idx2Lable[index] = lable
        bool_arr = lables == lable
        selected_sentences = dataSet[bool_arr]
        classNumber = selected_sentences.shape[0]
        prob_Ci = selected_sentences.shape[0] / m
        #print("Lable : ",lable)
        #total_cond_prob = 1
        total_cond_prob = 0 # log scale
        for attributeIdx in range(dataSet.shape[1]):
            value = testVec[attributeIdx]
            matched = selected_sentences[:,attributeIdx] # return column vector
            selector = matched == value
            matched = matched[selector]
            count = matched.shape[0]
            cond_prob = k + count / 2k + classNumber
            """
            cond_prob = count / classNumber
            if cond_prob ==0:
                cond_prob = 0.01
            """
            #total_cond_prob *= cond_prob
            total_cond_prob += -np.log(cond_prob) # log scale
        total_cond_prob *= prob_Ci
        prob_per_classes.append(total_cond_prob)
        index+=1
    idx = np.argmax(prob_per_classes)
    idx = np.argmin(prob_per_classes)
    print(prob_per_classes)
    prediction = Idx2Lable[idx]
    return prediction
    
    
testUnit = ['I','love','my','dog']
#testUnit =['stupid','dog']
testVec = sentence2vec(tokens,testUnit)
testVec = np.array(testVec)
classify(dataSet,lables,testVec)

[5.4409454422015333, 12.395169719013301]


0